sonar.organization=xoops
sonar.projectKey=XOOPS_smarty-extensions
sonar.projectName=XOOPS Smarty Extensions

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.php.version=8.2
sonar.php.coverage.reportPaths=build/logs/clover.xml

sonar.exclusions=vendor/**,build/**
